num1 = int(input("Enter the Number 1: "))
num2 = int(input("Enter the Number 2: "))
total = sum([num1, num2])
count = len([num1])
maximum = max([num1,num2])
minimum = min([num1,num2])
print("Sum:",total)
print("Length:",count)
print("Maximum:",maximum)
print("Minimum:",minimum)
